#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
# nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_INTERNAL_IP $OPENSHIFT_REPO_DIR/diy > $OPENSHIFT_HOMEDIR/diy-0.1/logs/server.log 2>&1 &

#source ${OPENSHIFT_REPO_DIR}/misc/virtenv/bin/activate
#export PYTHONPATH="${OPENSHIFT_REPO_DIR}/misc/virtenv/lib/python2.7/site-packages"
#nohup ${OPENSHIFT_REPO_DIR}/diy/test.py > $OPENSHIFT_HOMEDIR/diy-0.1/logs/test.log 2>&1 &

echo "Add some to start hook"

